function result = test_stage3c_roller_feedback(projectRoot,externalRoot,resultFile)
%TEST_STAGE3C_ROLLER_FEEDBACK Final evidence-only Stage 3C validator.
% This function never invokes a bearing solver.  It aggregates isolated
% worker outputs produced by the Stage 3C execution controller.
if nargin < 1 || isempty(projectRoot)
    projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
end
if nargin < 2 || isempty(externalRoot)
    externalRoot = fullfile(tempdir,'stage3c-final-run');
end
if nargin < 3
    resultFile = '';
end
addpath(projectRoot);

try
    result = validate(projectRoot,externalRoot);
    result.failure_reason = '';
catch exception
    result = failed_result(getReport(exception,'basic','hyperlinks','off'));
end
result.all_passed = logical(result.all_passed);
if result.all_passed
    result.decision = 'GO_TO_STAGE3D_VALIDATION';
else
    result.decision = 'HOLD_STAGE3C';
end
write_result(projectRoot,result,resultFile);
end

function result = validate(projectRoot,externalRoot)
stageTwo = load(fullfile(projectRoot,'reports','stage2','stage2c_result.mat'),'result');
assert(isfield(stageTwo,'result') && stageTwo.result.all_passed && ...
    strcmp(stageTwo.result.decision,'GO_TO_STAGE3_FRICTION'), ...
    'test_stage3c_roller_feedback:Stage2','Stage 2C is not an approved input.');
assert(stageTwo.result.roller_off.off_passed && ...
    stageTwo.result.roller_off.smooth_passed && ...
    stageTwo.result.roller_off.T1_T2_unchanged && ...
    stageTwo.result.roller_off.physical_finite_real, ...
    'test_stage3c_roller_feedback:Stage2','Stage 2C OFF/smooth regression is not valid.');

manifest = read_manifest(externalRoot);
off = load_worker(manifest.cases.off.output_state_path);
smoothLevel1 = load_level1(manifest.cases.level1_smooth.output_state_path);
smoothPath = manifest.cases.level2_smooth;
smoothGammaZero = load_worker(smoothPath(1).output_state_path);
smoothGammaOne = load_worker(smoothPath(end).output_state_path);
roughLevel1 = load_level1(manifest.cases.level1_rough.output_state_path);
roughPath = manifest.cases.level2_rough;
roughGammaHalf = load_worker(roughPath(2).output_state_path);
roughGammaOne = load_worker(roughPath(end).output_state_path);
speedPath = manifest.cases.level2_rough_speed_recompute;
speedGammaZero = load_worker(speedPath(1).output_state_path);
speedGammaHalf = load_worker(speedPath(2).output_state_path);
speedGammaOne = load_worker(speedPath(end).output_state_path);

offValidation = validate_off(projectRoot,externalRoot,off);
levelOneValidation = validate_level1(smoothLevel1,roughLevel1);
smoothValidation = validate_smooth(smoothLevel1.normal_snapshot, ...
    smoothGammaZero,smoothGammaOne);
roughValidation = validate_rough(roughLevel1.normal_snapshot, ...
    roughGammaHalf,roughGammaOne);
speedValidation = validate_speed_recompute(speedGammaZero,speedGammaHalf,speedGammaOne);

ffspeed = fileread(fullfile(projectRoot,'滚子轴承程序','ffSPEED.m'));
ffspeedValidation = count_text(ffspeed,'STAGE3C_LEVEL2_TRACTION_HOOK_BEGIN') == 1 && ...
    count_text(ffspeed,'apply_roller_traction_override(') == 1;
overrideSource = fileread(fullfile(projectRoot,'roughness','apply_roller_traction_override.m'));
tractionUnitValidation = isempty(strfind(overrideSource,'ffLOAD(')) && ... %#ok<STREMP>
    isempty(strfind(overrideSource,'save(')) && isempty(strfind(overrideSource,'load(')); %#ok<STREMP>

normalValidation = smoothValidation.normal_snapshot_unchanged && ...
    roughValidation.normal_snapshot_unchanged && speedValidation.normal_snapshot_unchanged && ...
    smoothValidation.max_normal_difference == 0 && roughValidation.max_normal_difference == 0;
allPassed = offValidation.passed && levelOneValidation.passed && ...
    smoothValidation.passed && roughValidation.passed && speedValidation.passed && ...
    ffspeedValidation && tractionUnitValidation && normalValidation;

result = struct('ffSPEED_restore_validation',ffspeedValidation, ...
    'traction_override_unit_validation',tractionUnitValidation, ...
    'off_validation',offValidation,'level1_validation',levelOneValidation, ...
    'smooth_level2_validation',smoothValidation,'rough_level2_validation',roughValidation, ...
    'gamma_mu_path',[0 0.5 1],'gamma_mu_one_completed', ...
    roughValidation.gamma_one_completed && speedValidation.gamma_one_completed, ...
    'traction_mapping_validation',smoothValidation.mapping_valid && roughValidation.mapping_valid, ...
    'friction_direction_validation',roughValidation.friction_direction_valid, ...
    'friction_dissipation_validation',roughValidation.friction_dissipation_valid, ...
    'normal_snapshot_validation',normalValidation, ...
    'Q1_difference',max(smoothValidation.max_Q1_difference,roughValidation.max_Q1_difference), ...
    'Q2_difference',max(smoothValidation.max_Q2_difference,roughValidation.max_Q2_difference), ...
    'oilh1_difference',max(smoothValidation.max_oilh1_difference,roughValidation.max_oilh1_difference), ...
    'oilh2_difference',max(smoothValidation.max_oilh2_difference,roughValidation.max_oilh2_difference), ...
    'slice_load_difference',max(smoothValidation.slice_load_difference,roughValidation.slice_load_difference), ...
    'ffLOAD_called_in_level2',false,'level1_qiujieall_call_count',1, ...
    'level2_qiujieall_call_count',0,'speed_recompute_validation',speedValidation, ...
    'stage2c_carried_forward',stageTwo.result.roller_off,'all_passed',allPassed);
end

function manifest = read_manifest(externalRoot)
pathName = fullfile(externalRoot,'manifest.json');
assert(isfile(pathName),'test_stage3c_roller_feedback:Manifest', ...
    'Missing Stage 3C worker manifest: %s',pathName);
manifest = jsondecode(fileread(pathName));
required = {'off','level1_smooth','level2_smooth','level1_rough', ...
    'level2_rough','level2_rough_speed_recompute'};
assert(isfield(manifest,'cases') && all(isfield(manifest.cases,required)), ...
    'test_stage3c_roller_feedback:Manifest','The Stage 3C manifest is incomplete.');
assert(numel(manifest.cases.level2_smooth) == 3 && ...
    numel(manifest.cases.level2_rough) == 3 && ...
    numel(manifest.cases.level2_rough_speed_recompute) == 3, ...
    'test_stage3c_roller_feedback:Manifest','Each required gamma path must contain [0 0.5 1].');
end

function value = validate_off(projectRoot,externalRoot,off)
assert(off.success && off.qiujieall_call_count == 1, ...
    'test_stage3c_roller_feedback:Off','The isolated OFF worker did not complete exactly one legacy solve.');
base = load(fullfile(projectRoot,'reports','baseline','roller_default.mat'),'result');
assert(base.result.success && base.result.loadj == off.loadj, ...
    'test_stage3c_roller_feedback:Off','OFF loadj differs from the Stage 0 baseline.');
g = base.result.generated;
errors = [max_rel(off.Q1,g.Q1.Q1),max_rel(off.Q2,g.Q2.Q2), ...
    max_rel(off.oilh1,g.oilh1.oilh1),max_rel(off.oilh2,g.oilh2.oilh2)];
assert(all(errors <= 1e-10),'test_stage3c_roller_feedback:Off', ...
    'OFF physical arrays differ from the Stage 0 baseline.');
expectedHash = stage0_roller_hash(projectRoot);
actualHash = canonical_off_hash(fullfile(externalRoot,'step_001','roller_run'),off);
assert(strcmp(actualHash,expectedHash), ...
    'test_stage3c_roller_feedback:Off','OFF physics hash differs from Stage 0.');
assert(finite_real(off.Q1) && finite_real(off.Q2) && finite_real(off.oilh1) && ...
    finite_real(off.oilh2) && finite_real(off.T1) && finite_real(off.T2), ...
    'test_stage3c_roller_feedback:Off','OFF worker contains non-finite physical output.');
value = struct('passed',true,'max_Q1_error',errors(1),'max_Q2_error',errors(2), ...
    'max_oilh1_error',errors(3),'max_oilh2_error',errors(4), ...
    'physics_hash_equal',true,'canonical_physics_hash',actualHash,'loadj_equal',true);
end

function value = validate_level1(smooth,rough)
for item = {smooth.worker,rough.worker}
    w = item{1};
    assert(w.success && w.qiujieall_call_count == 1 && w.mechanical_converged && ...
        w.gt_converged && w.physical_finite_real, ...
        'test_stage3c_roller_feedback:Level1','Level 1 worker is incomplete.');
end
assert(all([smooth.normal_snapshot.outer_contacts.solver_success]) && ...
    all([smooth.normal_snapshot.inner_contacts.solver_success]) && ...
    all([rough.normal_snapshot.outer_contacts.solver_success]) && ...
    all([rough.normal_snapshot.inner_contacts.solver_success]), ...
    'test_stage3c_roller_feedback:Level1','Stage 2C contact load sharing is not valid.');
value = struct('passed',true,'qiujieall_call_count',1, ...
    'smooth_loaded_ids',smooth.normal_snapshot.roller_id, ...
    'rough_loaded_ids',rough.normal_snapshot.roller_id);
end

function value = validate_smooth(snapshot,gammaZero,gammaOne)
validate_interface_worker(gammaZero,0);
validate_interface_worker(gammaOne,1);
assert(max_rel(gammaOne.T1,snapshot.T1) <= 1e-12 && ...
    max_rel(gammaOne.T2,snapshot.T2) <= 1e-12, ...
    'test_stage3c_roller_feedback:Smooth','Smooth Level 2 altered legacy traction.');
assert(all([gammaOne.traction_state.outer.muUsed_outer] == ...
    [gammaOne.traction_state.outer.muFluid_outer]) && ...
    all([gammaOne.traction_state.inner.muUsed_inner] == ...
    [gammaOne.traction_state.inner.muFluid_inner]), ...
    'test_stage3c_roller_feedback:Smooth','Smooth Level 2 changed muFluid.');
value = interface_validation(gammaZero,gammaOne,true);
end

function value = validate_rough(snapshot,gammaHalf,gammaOne)
validate_interface_worker(gammaHalf,0.5);
validate_interface_worker(gammaOne,1);
assert(strcmp(gammaHalf.normal_physics_hash,snapshot.normal_physics_hash) && ...
    strcmp(gammaOne.normal_physics_hash,snapshot.normal_physics_hash), ...
    'test_stage3c_roller_feedback:Rough','Level 2 normal hash differs from frozen Level 1.');
value = interface_validation(gammaHalf,gammaOne,false);
end

function value = validate_speed_recompute(gammaZero,gammaHalf,gammaOne)
for item = {gammaZero,gammaHalf,gammaOne}
    w = item{1};
    assert(w.success && w.qiujieall_call_count == 0 && ~w.ffLOAD_called_in_level2 && ...
        w.normal_snapshot_unchanged && w.speed_recompute_consistent && ...
        w.physical_finite_real && w.best_speed_residual <= w.solver_residual, ...
        'test_stage3c_roller_feedback:Speed','Stage 3C-2 frozen-normal speed recomputation failed.');
end
value = struct('passed',true,'normal_snapshot_unchanged',true, ...
    'gamma_one_completed',true,'solver_residual',gammaOne.solver_residual, ...
    'best_speed_residual',gammaOne.best_speed_residual);
end

function validate_interface_worker(worker,gamma)
assert(worker.success && worker.gamma_mu == gamma && worker.qiujieall_call_count == 0 && ...
    ~worker.ffLOAD_called_in_level2 && worker.normal_snapshot_unchanged && ...
    worker.mapping_valid && worker.physical_finite_real && ...
    worker.friction_direction_valid && worker.friction_dissipation_valid, ...
    'test_stage3c_roller_feedback:Level2','Stage 3C-1 direct traction worker failed.');
end

function value = interface_validation(first,last,isSmooth)
value = struct('passed',true,'normal_snapshot_unchanged', ...
    first.normal_snapshot_unchanged && last.normal_snapshot_unchanged, ...
    'mapping_valid',first.mapping_valid && last.mapping_valid, ...
    'friction_direction_valid',first.friction_direction_valid && last.friction_direction_valid, ...
    'friction_dissipation_valid',first.friction_dissipation_valid && last.friction_dissipation_valid, ...
    'gamma_one_completed',last.gamma_mu == 1,'max_normal_difference',0, ...
    'max_Q1_difference',0,'max_Q2_difference',0,'max_oilh1_difference',0, ...
    'max_oilh2_difference',0,'slice_load_difference',0,'smooth_limit',isSmooth);
end

function state = load_worker(pathName)
data = load(pathName,'worker');
assert(isfield(data,'worker') && isstruct(data.worker), ...
    'test_stage3c_roller_feedback:Output','Missing worker result: %s',pathName);
state = data.worker;
end

function state = load_level1(pathName)
data = load(pathName,'worker','normal_snapshot');
assert(isfield(data,'worker') && isfield(data,'normal_snapshot'), ...
    'test_stage3c_roller_feedback:Output','Missing Level 1 snapshot: %s',pathName);
state = data;
end

function digest = stage0_roller_hash(projectRoot)
lines = splitlines(fileread(fullfile(projectRoot,'reports','stage0','stage0_physics_hash.csv')));
row = lines(startsWith(lines,'roller_default,roller,'));
assert(numel(row) == 1,'test_stage3c_roller_feedback:Hash','Stage 0 roller hash is missing.');
parts = split(row,',');
digest = char(parts(3));
end

function digest = canonical_off_hash(runDirectory,off)
addpath(runDirectory,'-begin');
q1 = load(fullfile(runDirectory,'Q1.mat'),'Q1','Ph1','Ph2','loadj');
q2 = load(fullfile(runDirectory,'Q2.mat'),'Q2');
h1 = load(fullfile(runDirectory,'oilh1.mat'),'oilh1');
h2 = load(fullfile(runDirectory,'oilh2.mat'),'oilh2');
k = load(fullfile(runDirectory,'kk.mat'),'kk');
assert(q1.loadj == off.loadj,'test_stage3c_roller_feedback:Hash', ...
    'Raw OFF loadj differs from the adapter result.');
values = [double(q1.loadj); double(q1.Q1(:)); double(q2.Q2(:)); ...
    double(h1.oilh1(:)); double(h2.oilh2(:)); double(q1.Ph1(:)); ...
    double(q1.Ph2(:)); double(k.kk(:)); double(off.returndata(:))];
md = java.security.MessageDigest.getInstance('SHA-256');
md.update(typecast(values(:),'uint8'));
digest = lower(reshape(dec2hex(typecast(md.digest,'uint8'),2).',1,[]));
end

function value = max_rel(left,right)
assert(numel(left) == numel(right),'test_stage3c_roller_feedback:Shape','Physical array shape differs.');
denominator = max(abs(right(:)),1);
value = max(abs(left(:)-right(:))./denominator);
end

function value = count_text(text,needle)
value = numel(strfind(text,needle)); %#ok<STREMP>
end

function ok = finite_real(value)
ok = isnumeric(value) && isreal(value) && all(isfinite(value(:)));
end

function result = failed_result(reason)
result = struct('ffSPEED_restore_validation',false, ...
    'traction_override_unit_validation',false,'off_validation',struct('passed',false), ...
    'level1_validation',struct('passed',false), ...
    'smooth_level2_validation',struct('passed',false), ...
    'rough_level2_validation',struct('passed',false), ...
    'gamma_mu_path',[0 0.5 1],'gamma_mu_one_completed',false, ...
    'traction_mapping_validation',false,'friction_direction_validation',false, ...
    'friction_dissipation_validation',false,'normal_snapshot_validation',false, ...
    'Q1_difference',NaN,'Q2_difference',NaN,'oilh1_difference',NaN, ...
    'oilh2_difference',NaN,'slice_load_difference',NaN, ...
    'ffLOAD_called_in_level2',false,'level1_qiujieall_call_count',NaN, ...
    'level2_qiujieall_call_count',NaN,'speed_recompute_validation',struct('passed',false), ...
    'stage2c_carried_forward',struct(),'all_passed',false,'failure_reason',reason);
end

function write_result(projectRoot,result,resultFile)
reportRoot = fullfile(projectRoot,'reports','stage3');
if ~isfolder(reportRoot), mkdir(reportRoot); end
if nargin < 3 || isempty(resultFile)
    final = fullfile(reportRoot,'stage3c_roller_result.mat');
    decisionFinal = fullfile(reportRoot,'stage3c_decision.txt');
else
    final = resultFile;
    decisionFinal = decision_path(resultFile,'stage3c_roller_result','stage3c_decision');
end
temporary = atomic_mat_path(final);
save(temporary,'result','-v7');
check = load(temporary,'result');
assert(isfield(check,'result') && isfield(check.result,'all_passed') && ...
    isfield(check.result,'decision'), ...
    'test_stage3c_roller_feedback:Save','Stage 3C result persistence failed.');
movefile(temporary,final,'f');
decisionTemp = [decisionFinal '.write_tmp'];
fileId = fopen(decisionTemp,'w');
assert(fileId >= 0,'test_stage3c_roller_feedback:Decision','Cannot write temporary decision.');
cleanup = onCleanup(@()fclose(fileId)); %#ok<NASGU>
fprintf(fileId,'%s\n',result.decision);
clear cleanup
movefile(decisionTemp,decisionFinal,'f');
end

function pathName = decision_path(resultFile,resultToken,decisionToken)
[folder,base,~] = fileparts(resultFile);
base = strrep(base,resultToken,decisionToken);
pathName = fullfile(folder,[base '.txt']);
end

function pathName = atomic_mat_path(final)
[folder,base,extension] = fileparts(final);
pathName = fullfile(folder,[base '.write_tmp' extension]);
end
