function result = test_stage3b_ball_interface()
%TEST_STAGE3B_BALL_INTERFACE Verify frozen Level-2 ball traction state.
root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(root);
addpath(fullfile(root,'roughness'));

normal = struct('ball_id',[2;5], ...
    'outer',[contact(100,100,0,0.02,0.02); contact(80,80,0,0.03,0.03)], ...
    'inner',[contact(90,90,0,0.025,0.025); contact(70,70,0,0.028,0.028)]);
legacy = struct('ball_id',[5;2], ...
    'Touter',[2.4;2.0], 'Tinner',[1.96;2.25], ...
    'slip_outer',[-4;-3], 'slip_inner',[5;6]);
normalBefore = normal;
legacyBefore = legacy;
smooth = build_ball_traction_feedback_state(normal,legacy,0);
assert(isequaln(normal,normalBefore) && isequaln(legacy,legacyBefore), ...
    'test_stage3b_ball_interface:Mutation','The Level-2 interface must not mutate Stage 2 state.');
assert(all([smooth.outer.muUsed] == [smooth.outer.muFluid]) && ...
    all([smooth.inner.muUsed] == [smooth.inner.muFluid]) && ...
    all(abs([smooth.outer.Tused]-[smooth.outer.Tlegacy]) <= 1e-12) && ...
    all(abs([smooth.inner.Tused]-[smooth.inner.Tlegacy]) <= 1e-12), ...
    'test_stage3b_ball_interface:Smooth','The smooth Level-2 limit must equal legacy traction.');
half = build_ball_traction_feedback_state(normal,legacy,0.5);
assert(all(isfinite([half.outer.muUsed])) && all(isfinite([half.inner.muUsed])) && ...
    all([half.outer.muUsed] >= [half.outer.muFluid]) && ...
    all([half.inner.muUsed] >= [half.inner.muFluid]), ...
    'test_stage3b_ball_interface:Homotopy','The intermediate traction homotopy state is invalid.');

rough = normal;
rough.outer(1).Qfluid = 75; rough.outer(1).Qasperity = 25; rough.outer(1).muMix = 0.07;
rough.outer(2).Qfluid = 58; rough.outer(2).Qasperity = 22; rough.outer(2).muMix = 0.06;
rough.inner(1).Qfluid = 63; rough.inner(1).Qasperity = 27; rough.inner(1).muMix = 0.065;
rough.inner(2).Qfluid = 49; rough.inner(2).Qasperity = 21; rough.inner(2).muMix = 0.062;
rough.outer(1).chiA = 0.25; rough.outer(2).chiA = 22/80;
rough.inner(1).chiA = 0.30; rough.inner(2).chiA = 0.30;
mixed = build_ball_traction_feedback_state(rough,legacy,1);
outer = mixed.outer; inner = mixed.inner;
assert(all([outer.Tused] >= 0) && all([inner.Tused] >= 0) && ...
    all([outer.friction_power] <= 0) && all([inner.friction_power] <= 0) && ...
    all([outer.finite]) && all([inner.finite]), ...
    'test_stage3b_ball_interface:Physical','Mixed traction must be finite and dissipative.');
assert(all([outer.Qfluid]+[outer.Qasperity] == [outer.Qtotal]) && ...
    all([inner.Qfluid]+[inner.Qasperity] == [inner.Qtotal]) && ...
    isequal(mixed.ball_id(:),normal.ball_id(:)), ...
    'test_stage3b_ball_interface:NormalState','Level-2 traction must preserve Stage 2 normal state.');

result = struct('smooth_passed',true,'mixed_passed',true, ...
    'direction_passed',true,'dissipation_passed',true, ...
    'normal_state_unchanged',true,'smooth',smooth,'mixed',mixed);
end

function value = contact(Qtotal,Qfluid,Qasperity,muFluid,muMix)
value = struct('Qtotal',Qtotal,'Qfluid',Qfluid,'Qasperity',Qasperity, ...
    'chiA',Qasperity/Qtotal,'muFluid',muFluid,'muMix',muMix, ...
    'loadBalanceError',0);
end
