function result = test_stage3a_traction_shadow(outputRoot)
%TEST_STAGE3A_TRACTION_SHADOW Verify pure mixed-traction shadow behavior.
% The inputs below are immutable Stage 1/2 contact-state snapshots.  This
% test deliberately does not invoke a bearing mechanical solver or GT model.

root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(root);
addpath(fullfile(root,'roughness'));
if nargin < 1 || isempty(outputRoot)
    outputRoot = fullfile(root,'reports','stage3');
end
if ~isfolder(outputRoot), mkdir(outputRoot); end

try
    result = evaluate_shadow();
    result.all_passed = true;
    result.decision = 'GO_TO_STAGE3B_BALL';
catch exception
    result = struct('smooth_passed',false,'ball_passed',false, ...
        'roller_passed',false,'dissipation_passed',false, ...
        'normal_state_unchanged',false,'all_passed',false, ...
        'decision','HOLD_STAGE3A','failure_reason', ...
        getReport(exception,'basic','hyperlinks','off'));
    write_result(outputRoot,result);
    rethrow(exception);
end
write_result(outputRoot,result);
end

function result = evaluate_shadow()

smooth = struct( ...
    'Qtotal',[100;80], 'Qfluid',[100;80], 'Qasperity',[0;0], ...
    'muFluid',[0.020;0.035], 'muMix',[0.020;0.035], ...
    'Tlegacy',[2.0;2.8], 'relative_sliding_velocity',[-4;3]);
smoothBefore = smooth;
smoothState = build_mixed_traction_state(smooth);
assert(isequaln(smooth,smoothBefore), ...
    'test_stage3a_traction_shadow:Mutation','The pure traction builder mutated its input.');
assert(all(smoothState.Qasperity == 0) && all(smoothState.muMix == smoothState.muFluid), ...
    'test_stage3a_traction_shadow:SmoothMix','Smooth contacts must retain fluid traction.');
assert(max(abs(smoothState.Tcandidate-smoothState.Tlegacy)) <= 1e-12, ...
    'test_stage3a_traction_shadow:SmoothTraction','Smooth candidate traction must equal legacy traction.');
assert(all(smoothState.traction_direction == -sign(smooth.relative_sliding_velocity)), ...
    'test_stage3a_traction_shadow:Direction','Traction direction must oppose relative sliding.');
assert(all(smoothState.friction_power <= 0) && all(smoothState.finite), ...
    'test_stage3a_traction_shadow:Dissipation','Smooth traction must dissipate energy.');

ball = struct( ...
    'Qtotal',[150;120], 'Qfluid',[112;85], 'Qasperity',[38;35], ...
    'muFluid',[0.020;0.024], 'muMix',[0.071;0.068], ...
    'Tlegacy',[3.0;2.88], 'relative_sliding_velocity',[5;-6]);
ballBefore = ball;
ballState = build_mixed_traction_state(ball);
assert(isequaln(ball,ballBefore), ...
    'test_stage3a_traction_shadow:BallMutation','Ball normal state must remain unchanged.');
assert(all(ballState.Qfluid + ballState.Qasperity == ballState.Qtotal) && ...
    all(ballState.Tcandidate >= 0) && all(ballState.friction_power <= 0) && ...
    all(ballState.finite), ...
    'test_stage3a_traction_shadow:BallPhysics','Ball mixed traction state is invalid.');

% Explicit loadi -> loadii mapping: never align traction arrays by position.
loadi = [3;7];
loadii = [7;3;10];
T1 = [2.40;1.80;0.10];
T2 = [2.00;1.50;0.10];
Q1ii = [120;90;5];
Q2ii = [100;75;5];
[found,location] = ismember(loadi,loadii);
assert(all(found) && numel(unique(loadi)) == numel(loadi) && ...
    numel(unique(loadii)) == numel(loadii), ...
    'test_stage3a_traction_shadow:RollerMap','The roller identifiers must map one-to-one.');
rollerOuter = struct( ...
    'Qtotal',[90;120], 'Qfluid',[67;91], 'Qasperity',[23;29], ...
    'muFluid',T1(location)./Q1ii(location), 'muMix',[0.064;0.061], ...
    'Tlegacy',T1(location), 'relative_sliding_velocity',[-3;4]);
rollerInner = struct( ...
    'Qtotal',[75;100], 'Qfluid',[54;76], 'Qasperity',[21;24], ...
    'muFluid',T2(location)./Q2ii(location), 'muMix',[0.066;0.063], ...
    'Tlegacy',T2(location), 'relative_sliding_velocity',[2;-5]);
outerBefore = rollerOuter;
innerBefore = rollerInner;
outerState = build_mixed_traction_state(rollerOuter);
innerState = build_mixed_traction_state(rollerInner);
assert(isequal(location,[2;1]) && isequaln(rollerOuter,outerBefore) && isequaln(rollerInner,innerBefore), ...
    'test_stage3a_traction_shadow:RollerMapping','Roller traction must use the explicit identifier mapping.');
assert(all(outerState.Qfluid + outerState.Qasperity == outerState.Qtotal) && ...
    all(innerState.Qfluid + innerState.Qasperity == innerState.Qtotal) && ...
    all(outerState.friction_power <= 0) && all(innerState.friction_power <= 0) && ...
    all(outerState.finite) && all(innerState.finite), ...
    'test_stage3a_traction_shadow:RollerPhysics','Roller mixed traction state is invalid.');

result = struct('smooth_passed',true,'ball_passed',true,'roller_passed',true, ...
    'dissipation_passed',true,'normal_state_unchanged',true, ...
    'smooth',smoothState,'ball',ballState,'roller_outer',outerState, ...
    'roller_inner',innerState,'roller_id',loadi,'outer_to_inner_map',location);
end

function write_result(outputRoot,result)
tmp = fullfile(outputRoot,'stage3a_result.tmp.mat');
final = fullfile(outputRoot,'stage3a_result.mat');
if isfile(tmp), delete(tmp); end
save(tmp,'result','-v7');
check = load(tmp,'result');
assert(isfield(check,'result') && isfield(check.result,'all_passed') && ...
    isfield(check.result,'decision'), ...
    'test_stage3a_traction_shadow:Save','Temporary Stage 3A result is incomplete.');
movefile(tmp,final,'f');

decision = result.decision;
tmpDecision = fullfile(outputRoot,'stage3a_decision.tmp.txt');
finalDecision = fullfile(outputRoot,'stage3a_decision.txt');
fid = fopen(tmpDecision,'w');
assert(fid >= 0,'test_stage3a_traction_shadow:Decision','Cannot write temporary decision.');
cleanup = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s',decision);
clear cleanup
movefile(tmpDecision,finalDecision,'f');
assert(strcmp(fileread(finalDecision),decision), ...
    'test_stage3a_traction_shadow:Decision','Decision file content is invalid.');
end
