function result = test_stage3c_roller_interface(projectRoot)
%TEST_STAGE3C_ROLLER_INTERFACE Pure Level-2 roller traction-state contract.
% This test uses explicit interface fixtures only; no roller solver is called.

if nargin < 1 || isempty(projectRoot)
    projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
end
addpath(projectRoot);
addpath(fullfile(projectRoot,'roughness'));

smoothInput = fixture(false);
level1Snapshot = smoothInput;
smooth = build_roller_traction_feedback_state(smoothInput,0);
assert(isequaln(smoothInput,level1Snapshot), ...
    'test_stage3c_roller_interface:Mutation', ...
    'The pure interface must not mutate the Stage 2 input state.');
assert(all([smooth.outer.muUsed_outer] == [smooth.outer.muFluid_outer]) && ...
    all([smooth.inner.muUsed_inner] == [smooth.inner.muFluid_inner]) && ...
    all(abs([smooth.outer.Tused_outer]-[smooth.outer.Tlegacy_outer]) <= 1e-12) && ...
    all(abs([smooth.inner.Tused_inner]-[smooth.inner.Tlegacy_inner]) <= 1e-12), ...
    'test_stage3c_roller_interface:Smooth', ...
    'The smooth Level-2 limit must reproduce legacy traction exactly.');

half = build_roller_traction_feedback_state(fixture(true),0.5);
rough = build_roller_traction_feedback_state(fixture(true),1);
assert(isequal(rough.roller_id(:),[8;2;5]) && ...
    isequal([rough.outer.roller_id].',[8;2;5]) && ...
    isequal([rough.inner.roller_id].',[8;2;5]), ...
    'test_stage3c_roller_interface:RollerId', ...
    'Roller identifiers must remain in the explicit Stage 2 order.');
assert(all([half.outer.muUsed_outer] >= [half.outer.muFluid_outer]) && ...
    all([half.inner.muUsed_inner] >= [half.inner.muFluid_inner]) && ...
    all([rough.outer.muUsed_outer] == [rough.outer.muMix_outer]) && ...
    all([rough.inner.muUsed_inner] == [rough.inner.muMix_inner]), ...
    'test_stage3c_roller_interface:Homotopy', ...
    'The traction homotopy does not follow the required muUsed definition.');
assert(all([rough.outer.Tused_outer] == ...
    [rough.outer.Tlegacy_outer] + ...
    ([rough.outer.muUsed_outer]-[rough.outer.muFluid_outer]).*[rough.outer.Qtotal]) && ...
    all([rough.inner.Tused_inner] == ...
    [rough.inner.Tlegacy_inner] + ...
    ([rough.inner.muUsed_inner]-[rough.inner.muFluid_inner]).*[rough.inner.Qtotal]), ...
    'test_stage3c_roller_interface:Traction', ...
    'Tused must use the corresponding side-specific normal load and friction state.');
assert(all([rough.outer.friction_power] <= 0) && ...
    all([rough.inner.friction_power] <= 0) && ...
    all([rough.outer.finite]) && all([rough.inner.finite]) && rough.finite, ...
    'test_stage3c_roller_interface:Physical', ...
    'The interface must produce finite dissipative side-specific traction states.');

result = struct('source','INTERFACE_FIXTURE_ONLY_NO_ROLLER_SOLVER', ...
    'off_passed',true,'level1_passed',true,'smooth_passed',true, ...
    'rough_passed',true,'mapping_passed',true,'finite_passed',true, ...
    'smooth',smooth,'half',half,'rough',rough);
reportRoot = fullfile(projectRoot,'reports','stage3');
if ~isfolder(reportRoot), mkdir(reportRoot); end
temporary = fullfile(reportRoot,'stage3c_interface_result.tmp.mat');
final = fullfile(reportRoot,'stage3c_interface_result.mat');
save(temporary,'result','-v7');
check = load(temporary);
assert(isfield(check,'result') && check.result.rough_passed, ...
    'test_stage3c_roller_interface:Save','Interface result validation failed.');
movefile(temporary,final,'f');
end

function input = fixture(isRough)
ids = [8;2;5];
outer = side(ids,[100;80;60],[2;2.4;1.5],[-4;3;-2], ...
    [0.020;0.030;0.025],isRough,[0.070;0.060;0.055]);
inner = side(ids,[90;70;50],[1.8;1.4;1.25],[5;-1;2], ...
    [0.028;0.022;0.032],isRough,[0.068;0.052;0.070]);
input = struct('roller_id',ids,'outer',outer,'inner',inner);
end

function value = side(ids,Qtotal,Tlegacy,slip,muFluid,isRough,muMix)
if isRough
    Qasperity = [20;16;12];
else
    Qasperity = zeros(size(Qtotal));
    muMix = muFluid;
end
Qfluid = Qtotal-Qasperity;
value = struct('roller_id',ids,'Qtotal',Qtotal,'Qfluid',Qfluid, ...
    'Qasperity',Qasperity,'muFluid',muFluid,'muMix',muMix, ...
    'Tlegacy',Tlegacy,'slip_velocity',slip);
end
