function [T1Out,T2Out,report] = apply_roller_traction_override(T1Legacy,T2Legacy,loadi,loadii,tractionState,cfg)
%APPLY_ROLLER_TRACTION_OVERRIDE Pure frozen-state Level-2 traction mapper.
% The function never changes normal state; it only replaces loaded-contact
% traction magnitudes through explicit roller identifiers.

T1Out = T1Legacy;
T2Out = T2Legacy;
report = default_report(cfg,T1Legacy,T2Legacy);
try
    [enabled,level] = feedback_config(cfg);
    report.enabled = enabled;
    report.feedback_level = level;
    validate_legacy(T1Legacy,T2Legacy,loadi,loadii);

    if level == 0 || level == 1
        report.mapping_valid = true;
        report.legacy_unchanged = true;
        report.finite = true;
        report.success = true;
        report.message = 'Legacy traction retained for feedback level 0 or 1.';
        return;
    end
    assert(enabled && level == 2, ...
        'apply_roller_traction_override:Config', ...
        'Level-2 traction override requires enabled roughness feedback level 2.');

    [rollerId,outerUsed,innerUsed] = validate_snapshot(tractionState,loadi);
    [found,legacyLocation] = ismember(loadi(:),loadii(:));
    assert(all(found), ...
        'apply_roller_traction_override:RollerMap', ...
        'Every loaded roller must map from loadi to loadii.');
    [found,stateLocation] = ismember(loadi(:),rollerId);
    assert(all(found), ...
        'apply_roller_traction_override:RollerMap', ...
        'Every loaded roller must have a frozen traction state.');

    T1Out = T1Legacy;
    T2Out = T2Legacy;
    T1Out(legacyLocation) = outerUsed(stateLocation);
    T2Out(legacyLocation) = innerUsed(stateLocation);
    report.mapping_valid = true;
    report.outer_override_count = numel(legacyLocation);
    report.inner_override_count = numel(legacyLocation);
    report.legacy_unchanged = isequaln(T1Out,T1Legacy) && isequaln(T2Out,T2Legacy);
    report.finite = finite_real(T1Out) && finite_real(T2Out);
    report.used_frozen_snapshot = true;
    report.success = report.finite;
    report.message = 'Frozen Level-2 roller traction override applied.';
catch exception
    T1Out = T1Legacy;
    T2Out = T2Legacy;
    report.success = false;
    report.finite = false;
    report.message = exception.message;
end
end

function report = default_report(cfg,T1Legacy,T2Legacy)
report = struct('success',false,'enabled',false,'feedback_level',NaN, ...
    'mapping_valid',false,'outer_override_count',0,'inner_override_count',0, ...
    'legacy_unchanged',isequaln(T1Legacy,T1Legacy) && isequaln(T2Legacy,T2Legacy), ...
    'finite',false,'used_frozen_snapshot',false,'message','');
if isstruct(cfg) && isfield(cfg,'roughness') && isstruct(cfg.roughness) && ...
        isfield(cfg.roughness,'enabled')
    report.enabled = logical(cfg.roughness.enabled);
end
if isstruct(cfg) && isfield(cfg,'roughness') && isstruct(cfg.roughness) && ...
        isfield(cfg.roughness,'feedback_level')
    report.feedback_level = cfg.roughness.feedback_level;
end
end

function [enabled,level] = feedback_config(cfg)
assert(isstruct(cfg) && isfield(cfg,'roughness') && isstruct(cfg.roughness) && ...
    isfield(cfg.roughness,'enabled') && isfield(cfg.roughness,'feedback_level'), ...
    'apply_roller_traction_override:Config', ...
    'cfg.roughness.enabled and cfg.roughness.feedback_level are required.');
enabled = logical(cfg.roughness.enabled);
level = cfg.roughness.feedback_level;
assert(isscalar(level) && isnumeric(level) && isfinite(level) && ...
    ismember(level,[0 1 2]), ...
    'apply_roller_traction_override:Config', ...
    'feedback_level must be 0, 1, or 2.');
end

function validate_legacy(T1Legacy,T2Legacy,loadi,loadii)
assert(isnumeric(T1Legacy) && isnumeric(T2Legacy) && isvector(T1Legacy) && ...
    isvector(T2Legacy) && numel(T1Legacy) == numel(loadii) && ...
    numel(T2Legacy) == numel(loadii) && finite_real(T1Legacy) && ...
    finite_real(T2Legacy) && all(T1Legacy(:) >= 0) && all(T2Legacy(:) >= 0), ...
    'apply_roller_traction_override:LegacyTraction', ...
    'Legacy T1/T2 must be finite nonnegative vectors aligned with loadii.');
assert(isnumeric(loadi) && isnumeric(loadii) && isvector(loadi) && isvector(loadii) && ...
    finite_real(loadi) && finite_real(loadii) && all(loadi(:) == floor(loadi(:))) && ...
    all(loadii(:) == floor(loadii(:))) && numel(unique(loadi(:))) == numel(loadi) && ...
    numel(unique(loadii(:))) == numel(loadii), ...
    'apply_roller_traction_override:RollerMap', ...
    'loadi and loadii must contain unique finite integer roller identifiers.');
end

function [ids,outerUsed,innerUsed] = validate_snapshot(state,loadi)
assert(isstruct(state) && isfield(state,'roller_id') && isfield(state,'outer') && ...
    isfield(state,'inner') && isfield(state,'finite') && logical(state.finite), ...
    'apply_roller_traction_override:Snapshot', ...
    'A finite frozen roller traction state is required.');
ids = state.roller_id(:);
assert(numel(ids) == numel(loadi) && finite_real(ids) && ...
    all(ids == floor(ids)) && numel(unique(ids)) == numel(ids), ...
    'apply_roller_traction_override:RollerMap', ...
    'Frozen traction roller identifiers are invalid.');
assert(numel(state.outer) == numel(ids) && numel(state.inner) == numel(ids), ...
    'apply_roller_traction_override:Snapshot', ...
    'Frozen traction contact arrays do not match roller identifiers.');
outerUsed = zeros(numel(ids),1);
innerUsed = zeros(numel(ids),1);
for index = 1:numel(ids)
    assert(state.outer(index).roller_id == ids(index) && ...
        state.inner(index).roller_id == ids(index) && ...
        isfield(state.outer,'Tused_outer') && isfield(state.inner,'Tused_inner'), ...
        'apply_roller_traction_override:RollerMap', ...
        'Frozen outer/inner traction states are not aligned with roller_id.');
    outerUsed(index) = state.outer(index).Tused_outer;
    innerUsed(index) = state.inner(index).Tused_inner;
end
assert(finite_real(outerUsed) && finite_real(innerUsed) && ...
    all(outerUsed >= 0) && all(innerUsed >= 0), ...
    'apply_roller_traction_override:Snapshot', ...
    'Frozen Tused values must be finite nonnegative real values.');
end

function ok = finite_real(value)
ok = isnumeric(value) && isreal(value) && all(isfinite(value(:)));
end
