function tractionState = build_roller_traction_feedback_state(normalState,gammaMu)
%BUILD_ROLLER_TRACTION_FEEDBACK_STATE Pure Level-2 roller traction state.
% This consumes a frozen Stage 2C normal state and never changes old mechanics.

validateattributes(gammaMu,{'numeric'},{'real','finite','scalar','>=',0,'<=',1}, ...
    'build_roller_traction_feedback_state','gammaMu');
requiredTop = {'roller_id','outer','inner'};
assert(isstruct(normalState) && all(isfield(normalState,requiredTop)), ...
    'build_roller_traction_feedback_state:NormalState', ...
    'The frozen Stage 2C roller state is incomplete.');

rollerId = normalState.roller_id(:);
assert(~isempty(rollerId) && all(isfinite(rollerId)) && isreal(rollerId) && ...
    all(rollerId == floor(rollerId)) && numel(unique(rollerId)) == numel(rollerId), ...
    'build_roller_traction_feedback_state:RollerId', ...
    'Stage 2C roller identifiers must be unique finite integers.');

outerInput = validate_side(normalState.outer,rollerId,'outer');
innerInput = validate_side(normalState.inner,rollerId,'inner');
outer = repmat(empty_side('outer'),numel(rollerId),1);
inner = repmat(empty_side('inner'),numel(rollerId),1);
for index = 1:numel(rollerId)
    outer(index) = build_side(outerInput,index,gammaMu,'outer');
    inner(index) = build_side(innerInput,index,gammaMu,'inner');
end

tractionState = struct('roller_id',rollerId,'gamma_mu',gammaMu, ...
    'outer',outer,'inner',inner, ...
    'slip_direction',struct('outer',[outer.traction_direction].', ...
        'inner',[inner.traction_direction].'), ...
    'friction_power',struct('outer',[outer.friction_power].', ...
        'inner',[inner.friction_power].'), ...
    'finite',all([outer.finite]) && all([inner.finite]));
end

function side = validate_side(value,rollerId,sideName)
required = {'roller_id','Qtotal','Qfluid','Qasperity','muFluid','muMix', ...
    'Tlegacy','slip_velocity'};
assert(isstruct(value) && all(isfield(value,required)), ...
    'build_roller_traction_feedback_state:NormalState', ...
    'The frozen %s contact state is incomplete.',sideName);

side = struct();
for index = 1:numel(required)
    name = required{index};
    values = value.(name);
    assert(isnumeric(values) && isvector(values) && numel(values) == numel(rollerId), ...
        'build_roller_traction_feedback_state:NormalState', ...
        'The %s %s vector does not match the roller identifiers.',sideName,name);
    side.(name) = values(:);
end
assert(isequal(side.roller_id,rollerId), ...
    'build_roller_traction_feedback_state:RollerMap', ...
    'The %s contact state is not explicitly aligned with roller_id.',sideName);
values = [side.Qtotal side.Qfluid side.Qasperity side.muFluid side.muMix ...
    side.Tlegacy side.slip_velocity];
assert(all(isfinite(values(:))) && isreal(values) && all(side.Qtotal > 0) && ...
    all(side.Qfluid >= 0) && all(side.Qasperity >= 0) && ...
    all(side.muFluid >= 0) && all(side.muMix >= 0) && ...
    all(side.Tlegacy >= 0) && all(side.slip_velocity ~= 0), ...
    'build_roller_traction_feedback_state:Physical', ...
    'The frozen %s contact state is physically invalid.',sideName);
partition = abs(side.Qfluid + side.Qasperity - side.Qtotal) ./ ...
    max(abs(side.Qtotal),1);
assert(all(partition < 1e-6), ...
    'build_roller_traction_feedback_state:LoadBalance', ...
    'The frozen %s load partition is not conserved.',sideName);
end

function state = build_side(side,index,gammaMu,sideName)
muFluid = side.muFluid(index);
muMix = side.muMix(index);
qTotal = side.Qtotal(index);
legacy = side.Tlegacy(index);
slip = side.slip_velocity(index);
muUsed = muFluid + gammaMu*(muMix-muFluid);
% Keep gamma=0 legacy traction exact. No normal load is added at any gamma.
if gammaMu == 0
    used = legacy;
else
    used = legacy + (muUsed-muFluid)*qTotal;
end
direction = -sign(slip);
power = direction*used*slip;
finite = all(isfinite([qTotal side.Qfluid(index) side.Qasperity(index) ...
    muFluid muMix muUsed legacy used direction power])) && isreal(power) && ...
    used >= 0 && power <= 0;

suffix = lower(sideName);
state = struct('roller_id',side.roller_id(index),'Qtotal',qTotal, ...
    'Qfluid',side.Qfluid(index),'Qasperity',side.Qasperity(index), ...
    ['muFluid_' suffix],muFluid,['muMix_' suffix],muMix, ...
    ['muUsed_' suffix],muUsed,['Tlegacy_' suffix],legacy, ...
    ['Tused_' suffix],used,'slip_velocity',slip, ...
    'traction_direction',direction,'friction_power',power,'finite',finite);
end

function state = empty_side(sideName)
suffix = lower(sideName);
state = struct('roller_id',[],'Qtotal',[],'Qfluid',[],'Qasperity',[], ...
    ['muFluid_' suffix],[],['muMix_' suffix],[],['muUsed_' suffix],[], ...
    ['Tlegacy_' suffix],[],['Tused_' suffix],[],'slip_velocity',[], ...
    'traction_direction',[],'friction_power',[],'finite',false);
end
