function tractionState = build_ball_traction_feedback_state(normalState,legacy,gammaMu)
%BUILD_BALL_TRACTION_FEEDBACK_STATE Frozen Level-2 ball traction state.
% This pure function consumes an already-converged Stage 2 normal state.
% It does not alter normal load, film, geometry, speed, or solver state.

validateattributes(gammaMu,{'numeric'},{'real','finite','scalar','>=',0,'<=',1}, ...
    'build_ball_traction_feedback_state','gammaMu');
requiredNormal = {'ball_id','outer','inner'};
requiredLegacy = {'ball_id','Touter','Tinner','slip_outer','slip_inner'};
assert(isstruct(normalState) && all(isfield(normalState,requiredNormal)), ...
    'build_ball_traction_feedback_state:NormalState','Stage 2 ball normal state is incomplete.');
assert(isstruct(legacy) && all(isfield(legacy,requiredLegacy)), ...
    'build_ball_traction_feedback_state:Legacy','Legacy ball traction state is incomplete.');

ballId = normalState.ball_id(:);
assert(~isempty(ballId) && all(ballId == floor(ballId)) && ...
    numel(unique(ballId)) == numel(ballId), ...
    'build_ball_traction_feedback_state:BallId','Stage 2 ball identifiers must be unique integers.');
assert(numel(normalState.outer) == numel(ballId) && numel(normalState.inner) == numel(ballId), ...
    'build_ball_traction_feedback_state:NormalState','Contact-state length does not match ball identifiers.');
[found,location] = ismember(ballId,legacy.ball_id(:));
assert(all(found) && numel(unique(legacy.ball_id(:))) == numel(legacy.ball_id), ...
    'build_ball_traction_feedback_state:BallMap','Legacy traction cannot be mapped one-to-one by ball identifier.');

outer = repmat(empty_side(),numel(ballId),1);
inner = repmat(empty_side(),numel(ballId),1);
for index = 1:numel(ballId)
    outer(index) = side_state(normalState.outer(index),legacy.Touter(location(index)), ...
        legacy.slip_outer(location(index)),gammaMu,ballId(index));
    inner(index) = side_state(normalState.inner(index),legacy.Tinner(location(index)), ...
        legacy.slip_inner(location(index)),gammaMu,ballId(index));
end
tractionState = struct('ball_id',ballId,'gamma_mu',gammaMu, ...
    'outer',outer,'inner',inner,'finite',all([outer.finite]) && all([inner.finite]));
end

function state = side_state(normal,Tlegacy,slipVelocity,gammaMu,ballId)
required = {'Qtotal','Qfluid','Qasperity','muFluid','muMix','chiA','loadBalanceError'};
assert(all(isfield(normal,required)), ...
    'build_ball_traction_feedback_state:NormalState','Stage 2 contact state is incomplete.');
values = [normal.Qtotal normal.Qfluid normal.Qasperity normal.muFluid normal.muMix ...
    normal.chiA normal.loadBalanceError Tlegacy slipVelocity];
assert(all(isfinite(values)) && isreal(values) && normal.Qtotal > 0 && ...
    normal.Qfluid >= 0 && normal.Qasperity >= 0 && normal.muFluid >= 0 && ...
    normal.muMix >= 0 && normal.chiA >= 0 && normal.chiA <= 1 && ...
    normal.loadBalanceError < 1e-6 && Tlegacy >= 0 && slipVelocity ~= 0, ...
    'build_ball_traction_feedback_state:Physical','Invalid frozen ball contact state.');
partition = abs(normal.Qfluid + normal.Qasperity - normal.Qtotal) / max(abs(normal.Qtotal),1);
assert(partition < 1e-6, ...
    'build_ball_traction_feedback_state:LoadBalance','Stage 2 load partition is not conserved.');
assert(abs(normal.chiA-normal.Qasperity/normal.Qtotal) < 1e-6, ...
    'build_ball_traction_feedback_state:LoadBalance','Stage 2 asperity fraction is not conserved.');

muUsed = normal.muFluid + gammaMu*(normal.muMix-normal.muFluid);
mixed = build_mixed_traction_state(struct('Qtotal',normal.Qtotal, ...
    'Qfluid',normal.Qfluid,'Qasperity',normal.Qasperity, ...
    'muFluid',normal.muFluid,'muMix',normal.muMix, ...
    'Tlegacy',Tlegacy,'relative_sliding_velocity',slipVelocity));
assert(mixed.finite, ...
    'build_ball_traction_feedback_state:Physical','Stage 3A mixed traction state is invalid.');
% Tlegacy is retained at gamma=0 exactly; at gamma=1 the incremental mixed
% traction is (muMix-muFluid)*Qtotal.  Thus no additional normal load is added.
Tused = Tlegacy + (muUsed-normal.muFluid)*normal.Qtotal;
direction = mixed.traction_direction;
power = direction*Tused*slipVelocity;
finite = all(isfinite([normal.Qtotal normal.Qfluid normal.Qasperity normal.muFluid ...
    normal.muMix muUsed Tlegacy Tused direction power])) && isreal(power) && ...
    Tused >= 0 && power <= 0;

state = struct('ball_id',ballId,'Qtotal',normal.Qtotal,'Qfluid',normal.Qfluid, ...
    'Qasperity',normal.Qasperity,'chiA',normal.chiA,'muFluid',normal.muFluid, ...
    'muMix',normal.muMix,'muUsed',muUsed,'Tlegacy',Tlegacy,'Tused',Tused, ...
    'slip_velocity',slipVelocity,'traction_direction',direction, ...
    'friction_power',power,'finite',finite);
end

function state = empty_side()
state = struct('ball_id',[],'Qtotal',[],'Qfluid',[],'Qasperity',[], ...
    'chiA',[],'muFluid',[],'muMix',[],'muUsed',[],'Tlegacy',[], ...
    'Tused',[],'slip_velocity',[],'traction_direction',[], ...
    'friction_power',[],'finite',false);
end
