function state = build_mixed_traction_state(input)
%BUILD_MIXED_TRACTION_STATE Pure shadow evaluation of mixed-contact traction.
% INPUT carries already-validated Stage 1/2 normal-contact outputs.  Tlegacy
% and Tcandidate are traction magnitudes; traction_direction gives the signed
% force direction and friction_power is signed mechanical power (<= 0 means
% dissipation).  This function never writes to a bearing solver state.

required = {'Qtotal','Qfluid','Qasperity','muFluid','muMix','Tlegacy', ...
    'relative_sliding_velocity'};
assert(isstruct(input) && all(isfield(input,required)), ...
    'build_mixed_traction_state:Input','Missing required mixed-traction input field.');

shape = size(input.Qtotal);
for index = 1:numel(required)
    value = input.(required{index});
    validateattributes(value,{'numeric'},{'real','finite','nonempty'}, ...
        'build_mixed_traction_state',required{index});
    assert(isequal(size(value),shape), ...
        'build_mixed_traction_state:Shape','All contact fields must have the Qtotal shape.');
end

assert(all(input.Qtotal(:) > 0) && all(input.Qfluid(:) >= 0) && ...
    all(input.Qasperity(:) >= 0) && all(input.muFluid(:) >= 0) && ...
    all(input.muMix(:) >= 0) && all(input.Tlegacy(:) >= 0), ...
    'build_mixed_traction_state:PhysicalRange','Normal loads and traction magnitudes must be nonnegative.');
assert(all(input.relative_sliding_velocity(:) ~= 0), ...
    'build_mixed_traction_state:Sliding','A nonzero relative sliding velocity is required for traction direction.');

loadBalanceError = abs(input.Qfluid + input.Qasperity - input.Qtotal) ./ ...
    max(abs(input.Qtotal),1);
assert(all(loadBalanceError(:) < 1e-6), ...
    'build_mixed_traction_state:LoadBalance','Stage 2 load partition is not conserved.');

tractionDirection = -sign(input.relative_sliding_velocity);
candidate = input.muMix .* input.Qtotal;
power = tractionDirection .* candidate .* input.relative_sliding_velocity;
finite = all(isfinite([input.Qtotal(:); input.Qfluid(:); input.Qasperity(:); ...
    input.muFluid(:); input.muMix(:); input.Tlegacy(:); candidate(:); ...
    tractionDirection(:); power(:)])) && isreal(power) && all(power(:) <= 0);

state = struct('Qtotal',input.Qtotal,'Qfluid',input.Qfluid, ...
    'Qasperity',input.Qasperity,'muFluid',input.muFluid,'muMix',input.muMix, ...
    'Tlegacy',input.Tlegacy,'Tcandidate',candidate, ...
    'traction_direction',tractionDirection,'friction_power',power, ...
    'finite',finite);
end
